spring.application.name=map-service

# ===============================
# MQTT config
# ===============================
mqtt.broker=tcp://localhost:1883
mqtt.clientId=${spring.application.name:listener}-${random.uuid}
mqtt.topic=usv/AisMessage

# ===============================
# AIS config
# ===============================
ais.timezone=Asia/Shanghai

# ===============================
# LOG config
# ===============================
logging.level.com.whut.map=DEBUG