# ===============================
# DATABASE config
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/map_system_db
spring.datasource.username=myuser
spring.datasource.password=mypassword

# JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# MQTT config
# ===============================
mqtt.broker=tcp://localhost:1883
mqtt.clientId=${spring.application.name:listener}-${random.uuid}
mqtt.topics[0]=usv/AisMessage